using System.Reflection;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Istarion.Falcorm
{
  [Generator]
  public class Generator : IIncrementalGenerator
  {
    class MemberInfo
    {
      public string Name = null!, ColumnName = null!, Reader = null!;
      public string? Cast, Suffix;
      public bool IsKey, IsConcurrency;
      public int DatabaseGenerated;
      public ITypeSymbol Type = null!;
    }

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
      IncrementalValuesProvider<INamedTypeSymbol> typeSymbols = context.SyntaxProvider
          .CreateSyntaxProvider(
              predicate: (node, _) => node is ClassDeclarationSyntax cds && cds.AttributeLists.Count > 0,
              transform: (ctx, _) =>
              {
                var classDecl = (ClassDeclarationSyntax)ctx.Node;
                foreach (var attrList in classDecl.AttributeLists)
                  foreach (var attr in attrList.Attributes)
                  {
                    if (attr.Name.ToString() is "Table" or "TableAttribute")
                    {
                      var symbol = ctx.SemanticModel.GetDeclaredSymbol(classDecl);
                      return symbol as INamedTypeSymbol;
                    }
                  }
                return null;
              })
          .Where(s => s != null)!;

      var compilationAndTypes = context.CompilationProvider.Combine(typeSymbols.Collect());

      context.RegisterSourceOutput(compilationAndTypes, (spc, source) =>
      {
        var (_, types) = source;
        foreach (var type in types)
          GenerateMapper(spc, type);
      });
    }

    static IEnumerable<INamedTypeSymbol> GetTypeHierarchy(INamedTypeSymbol type)
    {
      for (var t = type; t != null; t = t.BaseType as INamedTypeSymbol)
        yield return t;
    }

    static string GetFullTypeName(INamedTypeSymbol type)
    {
      if (type.ContainingType is INamedTypeSymbol parent)
        return GetFullTypeName(parent) + "." + type.Name;
      return type.Name;
    }

    void GenerateMapper(SourceProductionContext context, INamedTypeSymbol type)
    {
      string typeName = GetFullTypeName(type);
      string ns = type.ContainingNamespace.IsGlobalNamespace ? "" : type.ContainingNamespace.ToString();
      string mapperClassName = $"DbMapper_{typeName.Replace(".", "_")}";

      var fields = from t in GetTypeHierarchy(type)
                   from f in t.GetMembers().OfType<IFieldSymbol>()
                   where f.DeclaredAccessibility == Accessibility.Public && !f.IsStatic && !f.IsReadOnly && !IsNotMapped(f)
                   let rm = GetReaderMethod(f.Type)
                   where rm.reader != null
                   select new MemberInfo { Name = f.Name, ColumnName = GetColumnName(f), Type = f.Type, Reader = rm.reader!, Cast = rm.cast, Suffix = rm.suffix, IsKey = GetColumnKey(f), IsConcurrency = GetColumnConcurrency(f), DatabaseGenerated = GetColumnGeneration(f) };

      var props = from t in GetTypeHierarchy(type)
                  from p in t.GetMembers().OfType<IPropertySymbol>()
                  where p.DeclaredAccessibility == Accessibility.Public && !p.IsStatic && p.SetMethod != null && !IsNotMapped(p)
                  let rm = GetReaderMethod(p.Type)
                  where rm.reader != null
                  select new MemberInfo { Name = p.Name, ColumnName = GetColumnName(p), Type = p.Type, Reader = rm.reader!, Cast = rm.cast, Suffix = rm.suffix, IsKey = GetColumnKey(p), IsConcurrency = GetColumnConcurrency(p), DatabaseGenerated = GetColumnGeneration(p) };

      var members = fields.Concat(props).Where(i => i.Reader != null).OrderBy(m => m.IsKey ? 0 : m.IsConcurrency ? 1 : 2).ThenBy(m => m.Name).ToList();

      if (members.Count == 0) return;

      var sb = new StringBuilder();
      sb.AppendLine("// <auto-generated/>");
      sb.AppendLine("#nullable enable");
      sb.AppendLine("#pragma warning disable");
      sb.AppendLine("using System;");
      sb.AppendLine("using System.Collections.Generic;");
      sb.AppendLine("using System.ComponentModel.DataAnnotations.Schema;");
      sb.AppendLine("using System.Data.Common;");
      sb.AppendLine("using System.Text;");
      sb.AppendLine("using System.Threading;");
      sb.AppendLine("using System.Threading.Tasks;");
      sb.AppendLine("using System.Runtime.CompilerServices;");
      sb.AppendLine("using Istarion.Falcorm;");
      sb.AppendLine("using Istarion.Falcorm.Internals;");

      var nsPrefix = "";

      if (!string.IsNullOrEmpty(ns))
      {
        sb.AppendLine();
        sb.AppendLine($"namespace {ns};");
        nsPrefix = ns + ".";
      }

      var modifier = GetAccessibilityModifier(GetEffectiveAccessibility(type));

      sb.AppendLine();
      sb.AppendLine($"{modifier} readonly struct {mapperClassName} : IDbMapper<{typeName}>");
      sb.AppendLine("{");
      sb.AppendLine($"  public static string TableName => \"{GetTableName(type)}\";");
      var hasDbGenerated = members.Where(i => i.DatabaseGenerated > 1 || i.IsConcurrency).Select(i => i.ColumnName).Any();

      sb.AppendLine($"  public static (int update, int keys, int generated) ColumnCounts => ({members.Count(i => !i.IsKey && !i.IsConcurrency && i.DatabaseGenerated == 0)},{members.Count(i => i.IsKey || i.IsConcurrency)},{members.Count(i => !i.IsConcurrency && !i.IsKey && i.DatabaseGenerated != 0)});");


      // BuildColumnMap
      GenerateCreateMap(members, sb);

      // Read
      GenerateRead(typeName, members, sb);

      if (!IsReadOnly(type))
      {
        GenerateStatements(typeName, members, sb);
      }
      sb.AppendLine("}");
      sb.AppendLine();

      sb.AppendLine($"public static partial class DbSessionExtensions");
      sb.AppendLine("{");
      GenerateTableProperty(typeName, mapperClassName, sb, modifier);
      sb.AppendLine();
      GenerateFindMethod(typeName, members, sb, modifier);
      sb.AppendLine("}");

      sb.AppendLine("#nullable restore");

      context.AddSource($"{nsPrefix}{typeName}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    public static string ToCamelCase(string text)
    {
      if (string.IsNullOrEmpty(text)) return text;

      var result = new StringBuilder();
      int i = 0;

      while (i < text.Length)
      {
        if (char.IsUpper(text[i]))
        {
          int start = i;
          while (i < text.Length && char.IsUpper(text[i]))
            i++;

          if (i < text.Length && char.IsLower(text[i]) && i - start > 1)
            i--;

          var word = text.Substring(start, i - start);

          result.Append(result.Length == 0
              ? word.ToLowerInvariant()
              : word);
        }
        else
        {
          if (result.Length == 0)
            result.Append(char.ToLowerInvariant(text[i]));
          else
            result.Append(text[i]);
          i++;
        }
      }

      return result.ToString();
    }
    private static void GenerateFindMethod(string typeName, List<MemberInfo> members, StringBuilder sb, string modifier)
    {
      var keys = members.Where(i => i.IsKey).Select(i => new { Name = "@" + ToCamelCase(i.Name), Column = i.ColumnName, Type = i.Type }).ToList();
      if (keys.Count == 0) return;

      var args = string.Join(", ", keys.Select(i => $"{i.Type} {i.Name}"));
      var args2 = string.Join(", ", keys.Select(i => i.Name));

      var where = $"$\"{string.Join(" and ", keys.Select(i => $"{i.Column} = {{{i.Name}}}"))}\"";

      var displayKeys = string.Join(", ", keys.Select(i => $"{i.Column}={{{i.Name}}}"));

      sb.AppendLine($"  extension(IDbTable<{typeName}> __s)");
      sb.AppendLine("  {");
      sb.AppendLine($"    {modifier} {typeName}? Find({args}) => __s.FirstOrDefault({where});");
      sb.AppendLine($"    {modifier} {typeName} Get({args}) => __s.Find({args2}) ?? throw new ArgumentException($\"{typeName} identified by [{displayKeys}] not found in database\");");
      sb.AppendLine("  }");
      sb.AppendLine();
      sb.AppendLine($"  extension(SqlBuilder<{typeName}> __s)");
      sb.AppendLine("  {");
      sb.AppendLine($"    {modifier} {typeName}? Find({args}) => __s.FirstOrDefault({where});");
      sb.AppendLine($"    {modifier} {typeName} Get({args}) => __s.Find({args2}) ?? throw new ArgumentException($\"{typeName} identified by [{displayKeys}] not found in database\");");
      sb.AppendLine("  }");
    }

    static void GenerateTableProperty(string typeName, string mapperClassName, StringBuilder sb, string modifier)
    {
      sb.AppendLine("  extension(DbSession session)");
      sb.AppendLine("  {");
      sb.AppendLine($"    {modifier} DbTable<{typeName}, {mapperClassName}> {Pluralize(typeName.Replace(".", "_"))} => new(session);");
      sb.AppendLine("  }");
    }

    private static void GenerateStatements(string typeName, List<MemberInfo> members, StringBuilder sb)
    {
      sb.AppendLine();

      var whereOptimistic = string.Join(" and ", members.Where(i => i.IsKey || i.IsConcurrency).Select(i => $"{{Dbo.CN(\"{i.ColumnName}\")}} = {{e.{i.Name}}}"));

      // Insert
      {
        var whereKeys = string.Join(" and ", members.Where(i => i.IsKey).Select(i => i.DatabaseGenerated == 1 && i.Reader == "GetInt32" ? $"({i.ColumnName} = SCOPE_IDENTITY())" : $"{{Dbo.CN(\"{i.ColumnName}\")}} = {{e.{i.Name}}}"));


        var refreshColumns = members.Where(i => i.DatabaseGenerated > 0 || i.IsConcurrency).Select(i => $"{{Dbo.CN(\"{i.ColumnName}\")}}").ToArray(); // calculated/identity/concurency token reload
        var columns = members.Where(i => i.DatabaseGenerated == 0 && !i.IsConcurrency);
        var columnsSb = string.Join(", ", columns.Select(i => $"{{Dbo.CN(\"{i.ColumnName}\")}}"));
        var valuesSb = string.Join(", ", columns.Select(i => $"{{e.{i.Name}}}"));

        sb.AppendLine($"  public static SqlBuilder<{typeName}> Insert(SqlBuilder<{typeName}> builder, {typeName} e, ref bool reload)");
        sb.AppendLine($"  {{");
        sb.AppendLine($"    builder = builder.Insert");
        sb.AppendLine($"     ($\"{columnsSb}\", ");
        sb.AppendLine($"      $\"{valuesSb}\");");
        if (refreshColumns.Length > 0)
        {
          var selectSb = string.Join(", ", refreshColumns);
          sb.AppendLine($"    return reload ? builder.Reload($\"{selectSb}\", $\"{whereKeys}\") : builder;");
        }
        else
        {
          sb.AppendLine($"    reload = false;");
          sb.AppendLine($"    return builder;");
        }
        sb.AppendLine($"  }}");
      }
      sb.AppendLine();

      {
        var whereKeys = string.Join(" and ", members.Where(i => i.IsKey).Select(i => $"{{Dbo.CN(\"{i.ColumnName}\")}} = {{e.{i.Name}}}"));

        sb.AppendLine($"  public static SqlBuilder<{typeName}> Delete(SqlBuilder<{typeName}> builder, {typeName} e) => builder.Delete($\"{whereOptimistic}\").Check();");
        sb.AppendLine();

        // Update 
        {
          var sqlSb = string.Join(", ", members.Where(i => i.DatabaseGenerated == 0 && !i.IsKey && !i.IsConcurrency).Select(i => $"{{Dbo.CN(\"{i.ColumnName}\")}} = {{e.{i.Name}}}"));
          var refreshColumns = members.Where(i => i.DatabaseGenerated > 1 || i.IsConcurrency).Select(i => $"{{Dbo.CN(\"{i.ColumnName}\")}}").ToArray(); // update reload

          sb.AppendLine($"  public static SqlBuilder<{typeName}>? Update(SqlBuilder<{typeName}> builder, {typeName} e, {typeName}? snapshot, ref bool reload)");
          sb.AppendLine($"  {{");
          sb.AppendLine($"    if (snapshot == default)");
          sb.AppendLine($"    {{");
          sb.AppendLine($"      builder = builder.Update($\"{sqlSb}\");");
          sb.AppendLine($"    }}");
          sb.AppendLine($"    else");
          sb.AppendLine($"    {{");
          foreach (var m in members.Where(i => i.DatabaseGenerated == 0 && !i.IsKey && !i.IsConcurrency))
          {
            sb.AppendLine($"      if (e.{m.Name} != snapshot.{m.Name}) builder = builder.Update($\"{{Dbo.CN(\"{m.ColumnName}\")}} = {{e.{m.Name}}}\");");
          }
          sb.AppendLine($"      if (!builder.HasUpdates) return null;");
          sb.AppendLine($"    }}");
          sb.AppendLine();
          sb.AppendLine($"    builder = builder.Where($\"{whereOptimistic}\");");


          if (refreshColumns.Length > 0)
          {
            var selectSb = string.Join(", ", refreshColumns);

            sb.AppendLine($"    return reload ? builder.Reload($\"{selectSb}\", $\"{whereKeys}\") : builder.Check();");
          }
          else
          {
            sb.AppendLine($"    reload = false;");
            sb.AppendLine($"    return builder.Check();");
          }
          sb.AppendLine($"  }}");
        }
        sb.AppendLine();
      }
    }

    private static void GenerateRead(string typeName, List<MemberInfo> members, StringBuilder sb)
    {
      sb.AppendLine($"  public static {typeName} Read(DbDataReader reader, Span<byte> indices, {typeName}? entity = null)");
      sb.AppendLine("  {");
      sb.AppendLine($"    var result = entity ?? new {typeName}();");
      sb.AppendLine($"    for (var i = 0; i < indices.Length; i++)");
      sb.AppendLine("    {");
      sb.AppendLine($"      switch (indices[i])");
      sb.AppendLine("      {");
      for (int idx = 0; idx < members.Count; idx++)
      {
        var member = members[idx];
        var propType = member.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var getter = member.Reader;
        var cast = member.Cast;
        var suffix = member.Suffix;

        if (IsNullable(member.Type))
          sb.AppendLine($"        case {idx}: if (reader.IsDBNull(i)) result.{member.Name} = default; else result.{member.Name} = {cast}reader.{getter}(i){suffix}; break;");
        else
          sb.AppendLine($"        case {idx}: result.{member.Name} = {cast}reader.{getter}(i){suffix}; break;");
      }
      sb.AppendLine("      }");
      sb.AppendLine("    }");
      sb.AppendLine("    return result;");
      sb.AppendLine("  }");
    }

    private static void GenerateCreateMap(List<MemberInfo> members, StringBuilder sb)
    {
      sb.AppendLine($"  public static void CreateMap(DbDataReader reader, Span<byte> indices)");
      sb.AppendLine("  {");
      sb.AppendLine("    indices.Fill((byte)0xFF);");
      sb.AppendLine("    for (int i = 0; i < reader.FieldCount; i++)");
      sb.AppendLine("    {");
      sb.AppendLine("      var name = reader.GetName(i);");


      var names = members.Select((m, idx) => new { Column = m.ColumnName, Idx = idx }).GroupBy(i => i.Column.Length).ToList();

      sb.AppendLine("      switch (name.Length)");
      sb.AppendLine("      {");

      foreach (var g in names.OrderBy(i => i.Key))
      {
        sb.AppendLine($"        case {g.Key}:");
        sb.AppendLine("        {");
        var f = true;
        foreach (var e in g.OrderBy(i => i.Column))
        {
          sb.AppendLine($"          {(f ? "" : "else ")}if (name.Equals(\"{e.Column}\", StringComparison.OrdinalIgnoreCase)) indices[i] = {e.Idx};");
          f = false;
        }
        sb.AppendLine("        }");
        sb.AppendLine("        break;");
      }
      sb.AppendLine("      }");
      sb.AppendLine("    }");
      sb.AppendLine("  }");
      sb.AppendLine();
    }

    string GetTableName(INamedTypeSymbol type)
    {
      var tableAttr = type.GetAttributes().FirstOrDefault(attr => attr.AttributeClass?.Name == "TableAttribute" || attr.AttributeClass?.Name == "Table");

      if (tableAttr != null)
      {
        var nameArg = tableAttr.NamedArguments.FirstOrDefault(kvp => kvp.Key == "Name").Value;

        if (nameArg.Value is string tableName && !string.IsNullOrEmpty(tableName))
          return tableName;

        if (tableAttr.ConstructorArguments.Length > 0 && tableAttr.ConstructorArguments[0].Value is string ctorName && !string.IsNullOrEmpty(ctorName))
          return ctorName;
      }

      return type.Name;
    }

    bool IsReadOnly(INamedTypeSymbol type)
      => type.GetAttributes().Any(attr => attr.AttributeClass?.Name == "ReadOnlyAttribute" || attr.AttributeClass?.Name == "ReadOnly");

    string GetColumnName(ISymbol symbol)
    {
      var columnAttr = symbol.GetAttributes().FirstOrDefault(attr => attr.AttributeClass?.Name == "ColumnAttribute" || attr.AttributeClass?.Name == "Column");

      if (columnAttr != null)
      {
        var nameArg = columnAttr.NamedArguments.FirstOrDefault(kvp => kvp.Key == "Name").Value;

        if (nameArg.Value is string columnName && !string.IsNullOrEmpty(columnName))
          return columnName;

        if (columnAttr.ConstructorArguments.Length > 0 && columnAttr.ConstructorArguments[0].Value is string ctorName && !string.IsNullOrEmpty(ctorName))
          return ctorName;
      }

      return symbol.Name;
    }

    bool GetColumnConcurrency(ISymbol symbol)
      => symbol.GetAttributes().Any(attr => attr.AttributeClass?.Name == "ConcurrencyCheckAttribute" || attr.AttributeClass?.Name == "ConcurrencyCheck");

    bool GetColumnKey(ISymbol symbol)
      => symbol.GetAttributes().Any(attr => attr.AttributeClass?.Name == "KeyAttribute" || attr.AttributeClass?.Name == "Key");

    bool IsNotMapped(ISymbol symbol)
      => symbol.GetAttributes().Any(attr => attr.AttributeClass?.Name == "NotMappedAttribute" || attr.AttributeClass?.Name == "NotMapped");

    int GetColumnGeneration(ISymbol symbol)
    {
      var attr = symbol.GetAttributes().FirstOrDefault(attr => attr.AttributeClass?.Name == "DatabaseGeneratedAttribute" || attr.AttributeClass?.Name == "DatabaseGenerated");

      if (attr != null && attr.ConstructorArguments.Length > 0 && attr.ConstructorArguments[0] is TypedConstant cnst)
        return (int)cnst.Value!;

      return 0;
    }

    static (string? reader, string? cast, string? suffix) GetReaderMethod(ITypeSymbol type)
      => GetReaderMethod(type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));

    static (string? reader, string? cast, string? suffix) GetReaderMethod(string type) => type switch
    {
      "string" or "string?" => ("GetString", null, null),
      "bool" or "bool?" => ("GetBoolean", null, null),
      "int" or "int?" => ("GetInt32", null, null),
      "byte[]" or "byte[]?" => ("GetFieldValue<byte[]>", null, null),
      "byte" or "byte?" => ("GetByte", null, null),
      "char" or "char?" => ("GetString", null, "[0]"),
      "long" or "long?" => ("GetInt64", null, null),
      "short" or "short?" => ("GetInt16", null, null),
      "decimal" or "decimal?" => ("GetDecimal", null, null),
      "double" or "double?" => ("GetDouble", null, null),
      "float" or "float?" => ("GetFloat", null, null),
      "global::System.DateTimeOffset" or "global::System.DateTimeOffset?" => ("GetFieldValue<DateTimeOffset>", null, null),
      "global::System.DateTime" or "global::System.DateTime?" => ("GetDateTime", null, null),
      "Guid" or "Guid?" or "global::System.Guid" => ("GetGuid", null, null),
      _ => (null, null, null)
    };

    static bool IsNullable(ITypeSymbol type)
    {
      if (type.NullableAnnotation == NullableAnnotation.Annotated)
        return true;

      var name = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
      return name.EndsWith("?", StringComparison.Ordinal);
    }

    public static string Pluralize(string word)
    {
      var dot = word.LastIndexOf('.');
      var prefix = dot >= 0 ? word.Substring(0, dot + 1) : "";
      var segment = dot >= 0 ? word.Substring(dot + 1) : word;

      var i = segment.Length - 1;
      while (i >= 0 && char.IsDigit(segment[i])) i--;
      var digitStart = i + 1;
      var segmentWord = digitStart < segment.Length ? segment.Substring(0, digitStart) : segment;
      var segmentDigits = digitStart < segment.Length ? segment.Substring(digitStart) : "";

      return prefix + PluralizeWord(segmentWord) + segmentDigits;
    }

    static string PluralizeWord(string word)
    {
      // Special cases for words ending in Person
      if (word.EndsWith("Person", StringComparison.OrdinalIgnoreCase))
        return word.Substring(0, word.Length - 6) + "Persons"; // "Active" + "Persons"

      if (word.EndsWith("Index", StringComparison.OrdinalIgnoreCase))
        return word.Substring(0, word.Length - 5) + "Indices";

      // Words ending in ch, sh, s, x, z -> add es
      if (word.EndsWith("ch") || word.EndsWith("sh") ||
          word.EndsWith("s") || word.EndsWith("x") || word.EndsWith("z"))
        return word + "es";

      // Country -> Countries (y -> ies, except after ay, ey, oy, uy)
      if (word.EndsWith("y") && word.Length >= 2 && !IsVowel(word[word.Length - 2]))
        return word.Substring(0, word.Length - 1) + "ies";

      // For everything else add s
      return word + "s";
    }

    private static bool IsVowel(char c)
    {
      return "aeiouAEIOU".IndexOf(c) >= 0;
    }

    /// <summary>Returns the most restrictive accessibility of the type and all its containing types (nested type cannot be more visible than parent).</summary>
    static Accessibility GetEffectiveAccessibility(INamedTypeSymbol type)
    {
      var acc = type.DeclaredAccessibility;
      for (var t = type.ContainingType as INamedTypeSymbol; t != null; t = t.ContainingType as INamedTypeSymbol)
        acc = MinAccessibility(acc, t.DeclaredAccessibility);
      return acc;
    }

    /// <summary>Returns the more restrictive of the two accessibilities (nested type cannot be more visible than parent).</summary>
    static Accessibility MinAccessibility(Accessibility a, Accessibility b)
    {
      static int Restrictiveness(Accessibility x) => x switch
      {
        Accessibility.Private => 0,
        Accessibility.ProtectedAndInternal => 1,
        Accessibility.Protected => 2,
        Accessibility.Internal => 3,
        Accessibility.ProtectedOrInternal => 4,
        Accessibility.Public => 5,
        _ => 3 // NotApplicable etc. -> treat as internal
      };
      return Restrictiveness(a) <= Restrictiveness(b) ? a : b;
    }

    static string GetAccessibilityModifier(Accessibility accessibility)
    {
      return accessibility switch
      {
        Accessibility.Public => "public",
        Accessibility.Internal => "internal",
        Accessibility.Private => "private",
        Accessibility.Protected => "protected",
        Accessibility.ProtectedOrInternal => "protected internal",
        Accessibility.ProtectedAndInternal => "private protected",
        _ => "internal"
      };
    }
  }
}